UIData: return static empty data model if value is null
eclipse-ee4j/mojarra pull request #5299
Opened 2023-08-11 14:19 UTC by pizzi80

https://github.com/eclipse-ee4j/mojarra/issues/5296

2023-08-11 15:46 UTC, melloware approved these changes

2023-08-13 14:57 UTC, melloware commented
Shouldn't this be done on the 2.3 branch so it can be promoted to 3.x an d4.x by BalusC?

2023-08-13 14:57 UTC, melloware requested changes
See comment

2023-09-02 21:15 UTC, BalusC commented
Already done via https://github.com/eclipse-ee4j/mojarra/pull/5304

2023-09-02 21:15 UTC, closed without merging