Add rowStatePreserved property to UIRepeat, exactly the same as UIData
eclipse-ee4j/mojarra pull request #5349
Opened 2023-11-04 17:06 UTC by BalusC

https://github.com/jakartaee/faces/issues/1263

2023-11-06 22:11 UTC, mnriem commented on impl/src/main/java/jakarta/faces/component/UIData.java
> +import static com.sun.faces.facelets.tag.faces.ComponentSupport.restoreFullDescendantComponentDeltaStates;
This won't work for 5.0 as UIData won't have access to com.sun.faces packages

2023-11-06 22:14 UTC, mnriem commented on impl/src/main/java/jakarta/faces/component/UIData.java
> +import static com.sun.faces.facelets.tag.faces.ComponentSupport.restoreFullDescendantComponentDeltaStates;
I suggest you move the necessary code into a private Utils class (or reuse one of the existing ones if possible) in the jakarta.faces.component package.

2023-11-06 22:14 UTC, mnriem requested changes
Make is so the UIData and UIRepeat both use a class from the jakarta.faces.component package (I suggest PackageUtils

2023-11-11 12:18 UTC, BalusC commented
Already took into account this while approving your PR :)

2023-11-11 12:40 UTC, mnriem approved these changes

2023-11-11 12:41 UTC, BalusC commented
@mnriem there you go: https://github.com/eclipse-ee4j/mojarra/pull/5353

2023-11-11 12:42 UTC, merged